$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - "*.xcconfig"
  - "*.xcodeproj"
  - "*.xib"
  - "*.storyboard"
  - "build"
  - "ephemeral"
  - "Podfile"
  - "gradlew"
  - "gradlew.bat"
  - "build.gradle.kts"
  - "*.iml"
  - "gradle.properties"
  - "*.plist"
  - "android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java"
  - "ios/Runner/GeneratedPluginRegistrant.m"
  - "macos/Pods"
words:
  - adamant
  - APPL
  - cocoapods
  - cupertino
  - dists
  - eseidel
  - firemaking
  - fluttercommunity
  - golbin
  - gradlew
  - hitpoints
  - melvor
  - mithril
  - modelable
  - pathprovider
  - persistor
  - pickpocketing
  - podfile
  - proguard
  - regen
  - regens
  - respawn
  - respawned
  - respawning
  - respawns
  - seidel
  - smithing
  - unequip
  - unequips
  - xcassets
  - xcconfig
  - xcodeproj
  - xcworkspace